#
#Thu Mar 05 07:21:53 UTC 2026
acceptInsecureCerts=false
browserName=chrome
goog\:chromeOptions={args\=[remote-allow-origins\=*, --headless\=chrome, --headless\=new,--no-sandbox,--disable-dev-shm-usage,--disable-gpu,--window-size\=1920,1080, --headless], extensions\=[]}
